config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted,
  # simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here,
  # as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get '/',                        to: 'sample#index'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'

    # TODO カート機能を実装する場合は修正すること
    post :add_cart,                 to: 'sample#add_cart'
    # potepan/products/:id
    resources :products,            only: [:show]

    # potepan/categories/:taxon_id
    resources :categories,          only: [:show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/potepan/product_decorator.rb
# modelを拡張する際に参考となるURL
# [https://guides.spreecommerce.org/developer/customization/logic.html]
module Potepan
  module ProductDecorator
    # 同じカテゴリー(taxons)に属している商品を、関連商品として取得するメソッド
    # 有効になった日時が新しい順で取得し、自身は含めない
    # 商品がカテゴリーに属していない、または取得件数の指定が[0]の場合は、空の配列を返却する
    #
    # @param  [Integer] fetch_count 取得件数（デフォルトは4件）
    # @return [Array<Spree::Product>] 関連商品
    def related_products(fetch_count: 4)
      # カテゴリーに属していない場合の商品全件検索を避けるため
      # [参考] solidus_core-2.7.0/app/models/spree/product/scopes.rb #in_taxons(L.75〜78)
      if taxons.blank? || fetch_count == 0
        return []
      end

      Spree::Product.
        in_taxons(taxons).
        available.
        where.not(id: id).
        includes(master: [:images, :default_price]).
        distinct.
        order(available_on: :desc).
        limit(fetch_count).
        to_a
    end
  end
end
Spree::Product.prepend Potepan::ProductDecorator

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  before_action :load_all_taxonomies, only: :show

  # 指定されたカテゴリーに所属する商品一覧を表示するアクション
  def show
    # 対象のレコードが存在しない場合は、ActiveRecord::RecordNotFoundが発生する
    @taxon = Spree::Taxon.includes(:products).find(params[:id])

    # 事前に画像と値段を読み込んでおく
    @products = @taxon.all_products.available.includes(master: [:images, :default_price])
  end

  private

  # 各カテゴリーが所属しているツリーを全件取得するメソッド
  # ツリーのルート分類及び、ルート分類の子分類を事前に読み込む
  #
  # @return [Array<Spree::Taxonomy>] 各分類が所属しているツリー一覧
  def load_all_taxonomies
    @taxonomies = Spree::Taxonomy.all.includes root: :children
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  # TODO 今後定数が増えた場合は、定数ファイルを作成するか、configやsettingslogicといったgemの使用を検討すること
  # config        [https://github.com/railsconfig/config]
  # settingslogic [https://github.com/binarylogic/settingslogic]
  # 関連商品表示件数
  RELATED_PRODUCTS_DISPLAY_COUNT = 4

  # 商品詳細表示ページ
  def show
    # 該当するレコードが存在しない場合、public/404.htmlを表示する
    @product = Spree::Product.available.friendly.find params[:id]

    # 同じカテゴリーに属している関連商品を取得
    @related_products = @product.related_products fetch_count: RELATED_PRODUCTS_DISPLAY_COUNT
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end

  # TODO カート機能を実装する際は修正すること
  def add_cart
    redirect_to(potepan_cart_page_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # 各ページの完全なタイトルを生成、返却するメソッド
  # 引数の前後に半角空白、全角空白が含まれている場合は、トリミングして完全なタイトルを生成する
  # 引数が以下の場合は、共通タイトルのみを返却する
  #   - nil
  #   - 空文字
  #   - 半角空白のみ
  #   - 全角空白のみ
  #   - 半角空白、全角空白混合
  #
  # @param  page_title [String] 各ページのタイトル
  # @return [String] 完全タイトル（各ページタイトル名 - 共通タイトル）
  # @return [String] 共通タイトル（引数が指定されていいない場合など）
  def generate_full_title(page_title: "")
    base_title = "BIGBAG Store"

    # 引数前後の半角空白、全角空白を空文字に置き換える
    trimmed_page_title = page_title.to_s.gsub(/(\A[[:space:]]+)|([[:space:]]+\Z)/, '')

    trimmed_page_title.empty? ? base_title : "#{trimmed_page_title} - #{base_title}"
  end

  # 該当のページが商品に関するページか判定するメソッド
  #
  # @return [Boolean] True  商品に関するページ
  # @return [Boolean] False それ以外のページ
  def product_pages?
    ['potepan/products', 'potepan/categories'].include?(controller_path)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= generate_full_title(page_title: yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="main-wrapper">
      <%= render(partial: 'layouts/headers/header') %>
      <%= yield %>
      <%= render(partial: 'layouts/footers/footer') %>
    </div>
    <%= render(partial: 'potepan/shared/modals/login') %>
    <%= render(partial: 'potepan/shared/modals/sign_up') %>
  </body>
</html>

app/views/layouts/footers/_footer.html.erb
<div id="footer" class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016-<%= Time.zone.now.year %> Copyright Potepan Store .</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/headers/_header.html.erb
<div class="header clearfix">
  <!-- TOPBAR -->
  <%= render(partial: 'layouts/headers/top_bar') %>

  <!-- NAVBAR -->
  <%= render(partial: 'layouts/headers/nav_bar') %>
</div>

app/views/layouts/headers/_nav_bar.html.erb
<nav class="navbar navbar-main navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to(potepan_path, class: 'navbar-brand') do %>
        <%= image_tag("img/logo.png", :alt => "") %>
      <% end %>
    </div>
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= 'active' if current_page?(potepan_path) %>">
          <%= link_to('Home', potepan_path) %>
        </li>
        <li class="dropdown megaDropMenu <%= 'active' if product_pages? %>">
          <%= link_to('Shop', 'javascript:void(0)', class: 'dropdown-toggle', 'data-toggle': 'dropdown', 'data-hover': 'dropdown', 'data-delay': '300', 'data-close-others': 'true', 'aria-expanded': 'false') %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/headers/_top_bar.html.erb
<div class="topBar">
  <div class="container">
    <div class="row">
      <div class="col-md-6 hidden-sm hidden-xs">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
      <div class="col-md-6 col-xs-12">
        <ul class="list-inline pull-right">
          <li></li>
          <li class="dropdown searchBox">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <form id="form01" action="product-grid-left-sidebar.html" method="post">
                <li>
                  <span class="input-group">
                    <input type="text" name="searchWord" class="form-control" placeholder="Search…" aria-describedby="basic-addon2">
                    <span onclick="FormSubmit();" class="input-group-addon addPointer" id="basic-addon2">検索</span>
                  </span>
                </li>
              </form>
            </ul>
          </li>
          <li class="dropdown">
            <%= link_to(potepan_cart_page_path, class: 'dropdown-toggle', 'data-toggle': 'dropdown disabled') do %>
              <i class="fa fa-shopping-cart"></i>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/potepan/categories/_filter.html.erb
<div class="row filterArea">
  <div class="col-xs-6">
    <select name="guiest_id1" id="guiest_id1" class="select-drop">
      <option value="0">並び替え</option>
      <option value="1">人気順</option>
      <option value="2">安い順</option>
      <option value="3">新着順</option>
      <option value="3">高い順</option>
    </select>
  </div>
  <div class="col-xs-6">
    <div class="btn-group pull-right" role="group">
      <button type="button" class="btn btn-default active" onclick="window.location.href='product_grid_left_sidebar.html'"><i class="fa fa-th" aria-hidden="true"></i><span>Grid</span></button>
      <button type="button" class="btn btn-default" onclick="window.location.href='product_list_left_sidebar.html'"><i class="fa fa-th-list" aria-hidden="true"></i><span>List</span></button>
    </div>
  </div>
</div>

app/views/potepan/categories/_sidebar.html.erb
<div class="col-md-3 col-sm-4 col-xs-12 sideBar">
  <div class="panel panel-default">
    <div class="panel-heading">商品カテゴリー</div>
    <div class="panel-body">
      <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
        <ul class="nav navbar-nav side-nav">
          <% taxonomies.each do |taxonomy| %>
            <li>
              <%= link_to 'javascript:;', 'data-toggle': 'collapse', 'data-target': "#taxonomy-#{taxonomy.id}" do %>
                <%= taxonomy.name %><i class="fa fa-plus"></i>
              <% end %>
              <ul id='taxonomy-<%= taxonomy.id %>' class="collapse collapseItem">
                <% root_taxon = taxonomy.root %>
                <% root_taxon.children.each do |taxon| %>
                  <li>
                    <%= link_to potepan_category_path(id: taxon.id) do %>
                      <i class="fa fa-caret-right" aria-hidden="true"></i><%= taxon.name %> <span>(<%= taxon.all_products.available.count %>)</span>
                    <% end %>
                  </li>
                <% end %>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="panel panel-default filterNormal">
    <div class="panel-heading">色から探す</div>
    <div class="panel-body">
      <ul class="list-unstyled">
        <li><a href="#">ブラック<span>(15)</span></a></li>
        <li><a href="#">ホワイト<span>(10)</span></a></li>
        <li><a href="#">レッド<span>(7)</span></a></li>
        <li><a href="#">ブルー<span>(12)</span></a></li>
        <li><a href="#">オレンジ<span>(12)</span></a></li>
      </ul>
    </div>
  </div>
  <div class="panel panel-default filterNormal">
    <div class="panel-heading">サイズから探す</div>
    <div class="panel-body">
      <ul class="list-unstyled clearfix">
        <li><a href="#">S<span>(15)</span></a></li>
        <li><a href="#">M<span>(10)</span></a></li>
        <li><a href="#">L<span>(7)</span></a></li>
        <li><a href="#">XL<span>(12)</span></a></li>
      </ul>
    </div>
  </div>
</div>

app/views/potepan/categories/grid/_product.html.erb
<div class="col-sm-4 col-xs-12">
  <div class="productBox">
    <div class="productImage clearfix">
      <%= link_to potepan_product_path(product) do %>
        <%= image_tag product.display_image.attachment.url %>
      <% end %>
    </div>
    <div class="productCaption clearfix">
      <%= link_to potepan_product_path(product) do %>
        <h5><%= product.name %></h5>
        <h3><%= product.display_price %></h3>
      <% end %>
    </div>
  </div>
</div>

app/views/potepan/categories/show.html.erb
<% provide :title, @taxon.name %>
<%= render 'potepan/shared/light_sections/page_header', page_title: @taxon.name, breadcrumb_active_list: @taxon.name %>
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <%= render 'sidebar', taxonomies: @taxonomies %>
      <div class="col-md-9 col-sm-8 col-xs-12">
        <%= render 'filter' %>
        <div class="row">
          <%= render partial: 'potepan/categories/grid/product', collection: @products %>
        </div>
      </div>
    </div>
  </div>
</section>
<%= render 'potepan/shared/light_sections/partner' %>

app/views/potepan/products/_main.html.erb
<div class="row singleProduct">
  <div class="col-xs-12">
    <div class="media">
      <div class="media-left productSlider">
        <div id="carousel" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <% product.images.each_with_index  do |image, index| %>
              <div class="item <%= 'active' if index.zero? %>" data-thumb="<%= index %>">
                <%= image_tag(image.attachment.url(:large)) %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="clearfix">
          <div id="thumbcarousel" class="carousel slide" data-interval="false">
            <div class="carousel-inner">
              <% product.images.each_with_index  do |image, index| %>
                <div data-target="#carousel" data-slide-to="<%= index %>" class="thumb">
                  <%= image_tag(image.attachment.url(:small)) %>
                </div>
              <% end %>
            </div>
            <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
          </div>
        </div>
      </div>
      <div class="media-body">
        <ul class="list-inline">
          <li>
            <%= link_to potepan_category_path id: product.taxons.first.id do %>
              <i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る
            <% end %>
          </li>
        </ul>
        <h2><%= product.name %></h2>
        <h3><%= product.display_price %></h3>
        <p><%= product.description %></p>
        <%= form_with(scope: :cart_form, url: potepan_add_cart_path, id: 'cart-form',local: true) do |f|%>
          <% variants_and_option_values = product.variants_and_option_values_for %>
          <% if variants_and_option_values.any? %>
            <span class="quick-drop">
              <%= f.collection_select(:variant, variants_and_option_values, :id, :options_text, { include_blank: false }, class: 'select-drop') %>
            </span>
          <% end %>
          <span class="quick-drop resizeWidth">
            <%= f.select(:amount, 1..10, { include_blank: false }, class: 'select-drop') %>
          </span>
          <div class="btn-area">
            <%= button_tag(type: :submit, class: 'btn btn-primary btn-block') do %>
              カートへ入れる<i class="fa fa-angle-right" aria-hidden="true"></i>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/potepan/products/_related_product.html.erb
<div class="col-md-3 col-sm-6 col-xs-12">
  <div class="productBox">
    <%= link_to potepan_product_path(related_product) do %>
      <div class="productImage clearfix">
        <%= image_tag(related_product.display_image.attachment :large, :alt => "products-img") %>
      </div>
      <div class="productCaption clearfix">
        <h5><%= related_product.name %></h5>
        <h3><%= related_product.display_price %></h3>
      </div>
    <% end %>
  </div>
</div>

app/views/potepan/products/show.html.erb
<% provide :title, @product.name %>
<%= render 'potepan/shared/light_sections/page_header', page_title: @product.name, breadcrumb_active_list: @product.name %>
<section class="mainContent clearfix">
  <div class="container">
    <%= render 'main', product: @product %>
    <div class="row productsContent">
      <div class="col-xs-12">
        <div class="page-header">
          <h4>関連商品</h4>
        </div>
      </div>
      <%= render partial: 'related_product', collection: @related_products %>
    </div>
  </div>
</section>

app/views/potepan/sample/checkout_complete.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>

    <!-- SITE TITTLE -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Order Completed - BIGBAG Store</title>

    <!-- PLUGINS CSS STYLE -->
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- GOOGLE FONT -->
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>

    <!-- CUSTOM CSS -->
    <link href="css/style.css" rel="stylesheet">
    <link rel="stylesheet" href="css/colors/default.css" id="option_color">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>

  <body>

    <div class="main-wrapper">

      <!-- HEADER -->
      <div class="header clearfix">

        <!-- TOPBAR -->
        <div class="topBar">
          <div class="container">
            <div class="row">
              <div class="col-md-6 hidden-sm hidden-xs">
                <ul class="list-inline">
                  <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                  <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                </ul>
              </div>
              <div class="col-md-6 col-xs-12">
                <ul class="list-inline pull-right">
                  <li><!-- <span><a data-toggle="modal" href='.login-modal'>ログイン</a><small>or</small><a data-toggle="modal" href='#signup'>新規登録</a></span> --></li>
                  <li class="dropdown searchBox">
                    <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
                    <ul class="dropdown-menu dropdown-menu-right">
                      <form  id="form01" action="product-grid-left-sidebar.html" method="post">
                      <li>
                        <span class="input-group">
                          <input type="text" name="searchWord" class="form-control" placeholder="Search…" aria-describedby="basic-addon2">
                          <span onclick="FormSubmit();" class="input-group-addon addPointer" id="basic-addon2">検索</span>
                        </span>
                      </li>
                      </form>
                    </ul>
                  </li>
                  <li class="dropdown">
                    <a href="cart-page.html" class="dropdown-toggle" data-toggle="dropdown disabled"><i class="fa fa-shopping-cart"></i></a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        <!-- NAVBAR -->
        <nav class="navbar navbar-main navbar-default" role="navigation">
          <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="index.html"><%= image_tag("logo.png") %></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
              <ul class="nav navbar-nav navbar-right">
                <li class=""><a href="index.html">Home</a></li>
                <li class="dropdown megaDropMenu">
                  <a href="product-grid-left-sidebar.html" class="dropdown-toggle"><b>Shop</b></a>
                </li>
              </ul>
            </div><!-- /.navbar-collapse -->
          </div>
        </nav>

      </div>

      <!-- LIGHT SECTION -->
      <section class="lightSection clearfix pageHeader">
        <div class="container">
          <div class="row">
            <div class="col-xs-6">
              <div class="page-title">
                <h2>thanks message</h2>
              </div>
            </div>
            <div class="col-xs-6">
              <ol class="breadcrumb pull-right">
                <li>
                  <a href="index.html">Home</a>
                </li>
                <li class="active">thanks message</li>
              </ol>
            </div>
          </div>
        </div>
      </section>

      <!-- MAIN CONTENT SECTION -->
      <section class="mainContent clearfix setp5">
        <div class="container">
          <div class="row">
            <div class="col-xs-12">
              <div class="thanksContent">
                <h2>Thank You !! <small>ご注文ありがとうございます。</small></h2>
                <h3>Shipping Details</h3>
                <div class="thanksInner">
                  <div class="row">
                    <div class="col-sm-6 col-xs-12 tableBlcok">
                      <address>
                        <span>Shipping address:</span> <a href="mailto:potepan@potepancamp.com">potepan@potepancamp.com</a> <br>
                        <span>Email:</span> <a href="mailto:potepan@potepancamp.com">potepan@potepancamp.com</a> <br>
                        <span>Phone:</span> +884 5452 6432
                      </address>
                    </div>
                    <div class="col-sm-6 col-xs-12">
                      <div class="well">
                        <h2><small>Order ID</small>9547</h2>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <!-- FOOTER -->
      <!-- COPY RIGHT -->
      <div id="footer" class="copyRight clearfix">
        <div class="container">
          <div class="row">
            <div class="col-sm-7 col-xs-12">
              <p>&copy; 2016-<%= Time.now.year %> Copyright Potepan Store .</p>
            </div>
            <div class="col-sm-5 col-xs-12">
              <ul class="list-inline">
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- LOGIN MODAL -->
    <div class="modal fade" id="login" tabindex="-1" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3 class="modal-title">log in</h3>
          </div>
          <div class="modal-body">
            <form action="" method="POST" role="form">
              <div class="form-group">
                <label for="login-email">Enter Email</label>
                <input type="email" class="form-control" id="login-email">
              </div>
              <div class="form-group">
                <label for="login-password">Password</label>
                <input type="password" class="form-control" id="login-password">
              </div>
              <div class="checkbox">
                <label>
                  <input type="checkbox"> Remember Me
                </label>
              </div>
              <button type="submit" class="btn btn-primary btn-block">log in</button>
              <button type="button" class="btn btn-link btn-block">Forgot Password?</button>
            </form>
          </div>
        </div>
      </div>
    </div>

    <!-- SIGN UP MODAL -->
    <div class="modal fade" id="signup" tabindex="-1" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3 class="modal-title">Create an account</h3>
          </div>
          <div class="modal-body">
            <form action="" method="POST" role="form">
              <div class="form-group">
                <label for="signup-email">Enter Email</label>
                <input type="email" class="form-control" id="signup-email">
              </div>
              <div class="form-group">
                <label for="signup-password">Password</label>
                <input type="password" class="form-control" id="signup-password">
              </div>
              <div class="form-group">
                <label for="signup-password-confirmation">Confirm Password</label>
                <input type="password" class="form-control" id="signup-password-confirmation">
              </div>
              <button type="submit" class="btn btn-primary btn-block">Sign up</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/potepan/shared/light_sections/_page_header.html.erb
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= page_title %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to('Home', potepan_path) %>
          </li>
          <li class="active"><%= breadcrumb_active_list %></li>
        </ol>
      </div>
    </div>
  </div>
</section>